# Generated by Django 5.1.2 on 2024-11-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
