# Generated by Django 5.1.2 on 2024-11-20 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default_book_image.jpg', upload_to='images/book_images/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='no title', max_length=200),
        ),
    ]
