# Generated by Django 5.1.2 on 2024-11-20 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_book_discount_book_image_book_price_book_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='store.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='store.category'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='no name', max_length=100),
        ),
    ]
