# Generated by Django 5.1.2 on 2024-11-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_book_author_book_category_alter_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='no title', max_length=100),
        ),
    ]
