# Generated by Django 5.1.2 on 2024-11-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='../default_book_image.jpg', upload_to='images/book_images/%y/%m/%d'),
        ),
    ]
