# Generated by Django 5.1.2 on 2024-11-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
