# Generated by Django 5.1.2 on 2024-11-05 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_discount_amount_book_price_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
