# Generated by Django 5.1.2 on 2024-11-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='no name', max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='no phone number currently', max_length=30, unique=True)),
                ('password', models.CharField(default='<django.db.models.fields.CharField><django.db.models.fields.CharField>', max_length=50)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
