# Generated by Django 5.1.2 on 2024-11-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=50),
        ),
    ]
