# Generated by Django 5.1.2 on 2024-11-20 18:59

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='Bla bla bla', max_length=50, validators=[sales.models.validatePassword]),
        ),
    ]
