# Generated by Django 5.1.2 on 2024-11-20 19:15

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, unique=True, validators=[sales.models.validatePhone]),
        ),
    ]
