# Generated by Django 5.1.2 on 2024-11-20 19:23

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, validators=[sales.models.validateUsername])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30, unique=True, validators=[sales.models.validatePhone])),
                ('password', models.CharField(max_length=30, validators=[sales.models.validatePassword])),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
