# Generated by Django 5.1.2 on 2024-11-20 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_item_order'),
        ('store', '0011_alter_author_name_alter_book_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.book'),
        ),
    ]
