# Generated by Django 5.1.2 on 2024-11-20 21:36

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=50, validators=[sales.models.validatePassword]),
        ),
    ]
