# Generated by Django 5.1.2 on 2024-11-20 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_order_customer'),
        ('store', '0011_alter_author_name_alter_book_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book'),
        ),
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order'),
        ),
    ]
