# Generated by Django 5.1.2 on 2024-11-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_item_book_alter_item_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total_price',
        ),
    ]
