# Generated by Django 5.1.2 on 2024-11-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_item_book_alter_item_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
